import logoWordmark from "@/assets/logo-wordmark.png";
import { Search, User, ShoppingCart } from "lucide-react";

const NAV_LINKS = [
  { label: "Home", href: "#" },
  { label: "Shop", href: "#" },
  { label: "Our Story", href: "#" },
  { label: "Routine Finder", href: "#" },
  { label: "Contact Us", href: "#" },
];

export function Header() {
  return (
    <header className="border-b border-bar-line bg-bar">
      <div className="mx-auto max-w-6xl px-5">
        {/* Top row: logo centered, icons right */}
        <div className="grid grid-cols-3 items-center py-4">
          <div />

          <a href="#" className="justify-self-center">
            <img
              src={logoWordmark}
              alt="Rosaleigh"
              width={220}
              height={61}
              className="h-[61px] w-[220px] object-contain"
            />
          </a>

          <div className="flex items-center justify-end gap-4">
            <button
              type="button"
              aria-label="Search"
              className="text-bar-foreground/90 transition-colors hover:text-highlight"
            >
              <Search className="h-5 w-5" />
            </button>
            <a
              href="#"
              aria-label="Account"
              className="text-bar-foreground/90 transition-colors hover:text-highlight"
            >
              <User className="h-5 w-5" />
            </a>
            <a
              href="#"
              aria-label="Cart"
              className="text-bar-foreground/90 transition-colors hover:text-highlight"
            >
              <ShoppingCart className="h-5 w-5" />
            </a>
          </div>
        </div>

        {/* Nav row */}
        <nav className="flex items-center justify-center gap-8 pb-4">
          {NAV_LINKS.map((link) => (
            <a
              key={link.label}
              href={link.href}
              className="text-sm font-medium text-bar-foreground/90 transition-colors hover:text-highlight"
            >
              {link.label}
            </a>
          ))}
        </nav>
      </div>
    </header>
  );
}

export const DISCLAIMER =
  "This analysis is generated by AI for general skincare guidance only. It is not a medical or dermatological diagnosis. Individual results vary. If you have a diagnosed skin condition, please consult a dermatologist before starting a new routine.";

const ABOUT_LINKS = [
  { label: "Home", href: "#" },
  { label: "Shop", href: "#" },
  { label: "Our Story", href: "#" },
  { label: "Routine Finder", href: "#" },
  { label: "Contact Us", href: "#" },
];

const CUSTOMER_CARE_LINKS = [
  { label: "Contact Us", href: "#" },
  { label: "Shipping Policy", href: "#" },
  { label: "Refund Policy", href: "#" },
  { label: "Privacy Policy", href: "#" },
  { label: "Terms of Service", href: "#" },
];

const SOCIALS = [
  {
    label: "Facebook",
    href: "https://www.facebook.com/profile.php?id=61593593936014",
    path: "M9.101 23.691v-7.98H6.627v-3.667h2.474v-1.58c0-4.085 1.848-5.978 5.858-5.978.401 0 .955.042 1.468.103a8.68 8.68 0 0 1 1.141.195v3.325a8.623 8.623 0 0 0-.653-.036 26.805 26.805 0 0 0-.653-.006c-.812 0-1.542.062-2.049.196-.512.135-.874.373-1.147.6-.273.227-.443.567-.539.985-.096.418-.144.913-.144 1.487v1.309h5.243l-.6 3.667h-4.643v7.98H9.101Z",
  },
  {
    label: "Pinterest",
    href: "https://pin.it/3zDGu3Ofw",
    path: "M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.162-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.15-2.911 1.014 0 1.503.762 1.503 1.673 0 1.019-.65 2.541-.983 3.951-.279 1.183.593 2.148 1.759 2.148 2.111 0 3.633-2.674 3.633-6.442 0-3.412-2.615-5.638-5.881-5.638-3.888 0-6.14 2.917-6.14 5.945 0 1.185.457 2.457 1.024 3.135.114.132.129.256.096.395-.104.437-.336 1.339-.379 1.526-.06.267-.19.323-.436.196-1.635-.769-2.656-3.174-2.656-5.098 0-4.019 2.926-7.694 8.415-7.694 4.42 0 7.856 3.148 7.856 7.354 0 4.395-2.774 7.929-6.615 7.929-1.292 0-2.51-.674-2.923-1.464l-.795 3.017c-.288 1.116-1.066 2.518-1.587 3.371 1.196.371 2.462.573 3.777.573 6.605 0 11.985-5.366 11.985-11.987C23.97 5.367 18.6 0 11.985 0h.032z",
  },
  {
    label: "Instagram",
    href: "https://www.instagram.com/rosaleigh_uk/",
    path: "M12 0C8.74 0 8.333.014 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.014 8.333 0 8.74 0 12s.014 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.986 8.74 24 12 24s3.667-.014 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.014-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.014 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z",
  },
  {
    label: "TikTok",
    href: "https://www.tiktok.com/@rosaleigh_uk",
    path: "M16.6 5.82c-1.007-1.024-1.575-2.415-1.575-3.82h-3.045v13.5c0 1.653-1.345 3-3 3s-3-1.347-3-3 1.345-3 3-3c.31 0 .61.048.892.135V9.55a6.32 6.32 0 0 0-.892-.065c-3.33 0-6.045 2.715-6.045 6.045s2.715 6.045 6.045 6.045 6.045-2.715 6.045-6.045V9.276a9.32 9.32 0 0 0 5.455 1.745V8c-1.517 0-2.926-.535-4.03-1.42-.32-.257-.612-.545-.87-.86l.02.1z",
  },
];

const PAYMENT_ICONS = ["Diners", "Discover", "Mastercard", "Visa", "PayPal", "Amex"];

export function Footer() {
  return (
    <footer className="border-t border-bar-line bg-bar">
      <div className="mx-auto max-w-6xl px-5 py-14">
        <div className="grid grid-cols-1 gap-10 md:grid-cols-5">
          {/* Logo + tagline */}
          <div className="md:col-span-1">
            <a href="#">
              <img
                src={logoWordmark}
                alt="Rosaleigh"
                width={200}
                height={55}
                className="h-[55px] w-[200px] object-contain"
              />
            </a>
            <p className="mt-4 text-sm leading-relaxed text-bar-muted">
              UK-based skincare, done properly. Every claim we make, we stand
              behind.
            </p>
          </div>

          {/* About */}
          <div>
            <h3 className="font-display text-lg text-bar-foreground">About</h3>
            <ul className="mt-4 space-y-2">
              {ABOUT_LINKS.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    className="text-sm text-bar-muted transition-colors hover:text-highlight"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Customer Care */}
          <div>
            <h3 className="font-display text-lg text-bar-foreground">
              Customer Care
            </h3>
            <ul className="mt-4 space-y-2">
              {CUSTOMER_CARE_LINKS.map((link) => (
                <li key={link.label}>
                  <a
                    href={link.href}
                    className="text-sm text-bar-muted transition-colors hover:text-highlight"
                  >
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Disclaimer */}
          <div>
            <h3 className="font-display text-lg text-bar-foreground">
              Disclaimer:
            </h3>
            <p className="mt-4 text-sm leading-relaxed text-bar-muted">
              {DISCLAIMER}
            </p>
          </div>

          {/* Subscribe */}
          <div>
            <h3 className="font-display text-lg text-bar-foreground">
              Subscribe to our emails
            </h3>
            <form className="mt-4 flex items-center border-b border-bar-line pb-1">
              <input
                type="email"
                placeholder="Email"
                aria-label="Email"
                className="w-full bg-transparent text-sm text-bar-foreground placeholder:text-bar-muted focus:outline-none"
              />
              <button
                type="submit"
                aria-label="Subscribe"
                className="text-bar-foreground transition-colors hover:text-highlight"
              >
                &rarr;
              </button>
            </form>
            <p className="mt-4 text-xs leading-relaxed text-bar-muted">
              Subscribe to our newsletter and get 10% off your first purchase
            </p>

            <div className="mt-6 flex items-center gap-3">
              {SOCIALS.map((social) => (
                <a
                  key={social.label}
                  href={social.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={(e) => {
                    e.preventDefault();
                    window.open(social.href, "_blank", "noopener,noreferrer");
                  }}
                  aria-label={social.label}
                  className="flex h-9 w-9 items-center justify-center rounded-full border border-bar-line text-bar-foreground transition-colors hover:border-highlight hover:text-highlight"
                >
                  <svg
                    viewBox="0 0 24 24"
                    fill="currentColor"
                    className="h-4 w-4"
                    aria-hidden="true"
                  >
                    <path d={social.path} />
                  </svg>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Bottom bar */}
      <div className="border-t border-bar-line">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-5 py-6 text-xs text-bar-muted md:flex-row">
          <p>
            &copy; {new Date().getFullYear()} Rosaleigh. All rights reserved.{" "}
            <a href="#" className="hover:text-highlight">
              Legal Notice
            </a>{" "}
            |{" "}
            <a href="#" className="hover:text-highlight">
              Cookies Policy
            </a>
          </p>
          <div className="flex flex-wrap items-center gap-2">
            {PAYMENT_ICONS.map((name) => (
              <span
                key={name}
                className="rounded border border-bar-line px-2 py-1 text-[10px] font-medium text-bar-muted"
              >
                {name}
              </span>
            ))}
          </div>
        </div>
      </div>
    </footer>
  );
}
