import { useEffect, useState } from "react";
import { Moon, Sun } from "lucide-react";
import logo from "@/assets/logo.png";

const THEME_KEY = "rosaleigh.theme";

export function Header() {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    const stored = window.localStorage.getItem(THEME_KEY);
    if (stored === "dark") {
      setDark(true);
      document.documentElement.classList.add("dark");
    }
  }, []);

  const toggle = () => {
    const next = !dark;
    setDark(next);
    document.documentElement.classList.toggle("dark", next);
    window.localStorage.setItem(THEME_KEY, next ? "dark" : "light");
  };

  return (
    <header className="border-b border-bar-line bg-bar">
      <div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4">
        <img
          src={logo}
          alt="Rosaleigh Cosmetics"
          width={1152}
          height={576}
          className="h-8 w-auto brightness-0 invert md:h-9"
        />
        <button
          type="button"
          onClick={toggle}
          aria-label={dark ? "Switch to light theme" : "Switch to dark theme"}
          className="rounded-full border border-bar-line p-2 text-bar-foreground transition-colors hover:bg-bar-line/50"
        >
          {dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
        </button>
      </div>
    </header>
  );
}

export const DISCLAIMER =
  "This analysis is generated by AI for general skincare guidance only. It is not a medical or dermatological diagnosis. Individual results vary. If you have a diagnosed skin condition, please consult a dermatologist before starting a new routine.";

export function Footer() {
  return (
    <footer className="mt-20 border-t border-bar-line bg-bar">
      <div className="mx-auto max-w-5xl space-y-4 px-5 py-10">
        <img
          src={logo}
          alt="Rosaleigh Cosmetics"
          width={1152}
          height={576}
          loading="lazy"
          className="h-7 w-auto brightness-0 invert"
        />
        <p className="max-w-2xl text-xs leading-relaxed text-bar-muted">{DISCLAIMER}</p>
        <p className="text-xs text-bar-muted">
          © {new Date().getFullYear()} Rosaleigh Cosmetics. Photographs are processed in your
          browser and never stored.
        </p>
      </div>
    </footer>
  );
}
